#!/usr/bin/env node
/**
 * scripts/clean-dist.js
 *
 * Remove the build output directory so the next build starts from a clean slate.
 * The release shape is regenerated by rollup + the shim-jar build; nothing here
 * is preserved across runs.
 */

import { rmSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT_DIR = dirname(fileURLToPath(import.meta.url));
const DIST_DIR = join(ROOT_DIR, '..', 'dist');

rmSync(DIST_DIR, { recursive: true, force: true });
console.log(`[clean] removed ${DIST_DIR}`);
